.TH NEOSC_SHA1HMNEXT 3  2015-04-10 "" ""
.SH NAME
neosc_sha1hmnext \- update SHA1 HMAC
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "void neosc_sha1hmnext(unsigned char *data, unsigned int length,"
.BI "                      NEOSC_SHA1DATA *ptr);"
.SH DESCRIPTION
The
.BR neosc_sha1hmnext()
function updates the HMAC processing structure with the given data of specified length.
.SH SEE ALSO
.BR neosc_sha1hmkey (3),
.BR neosc_sha1hminit (3),
.BR neosc_sha1hmend (3),
.BR neosc_sha1hmac (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
