.TH NEOSC_UTIL_URI2ID 3  2015-04-10 "" ""
.SH NAME
neosc_util_uri2id \- convert an url prefix to an uri identifier
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "int neosc_util_uri2id(char *uri);"
.SH DESCRIPTION
The
.BR neosc_util_uri2id()
function converts an url prefix to an uri identifier.
.SH RETURN VALUE
The
.BR neosc_util_uri2id()
function returns an url identifier or zero in case of an unknown prefix.
.SH SEE ALSO
.BR neosc_util_id2uri (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
