.TH NEOSC_PCSC_CLOSE 3  2015-04-10 "" ""
.SH NAME
neosc_pcsc_close \- close a CCID connection to a YubiKey
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "void neosc_pcsc_close(void *ctx);"
.SH DESCRIPTION
The
.BR neosc_pcsc_close()
function closes an existing CCID connection to a YubiKey.
.SH SEE ALSO
.BR neosc_pcsc_open (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
