.TH NEOSC_USB_CLOSE 3  2015-04-10 "" ""
.SH NAME
neosc_usb_close \- close a HID connection to a YubiKey
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "void neosc_usb_close(void *handle);"
.SH DESCRIPTION
The
.BR neosc_usb_close()
function closes an existing HID connection to a YubiKey.
.SH SEE ALSO
.BR neosc_usb_open (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
