.TH NEOSC_PCSC_LOCK 3  2015-04-10 "" ""
.SH NAME
neosc_pcsc_lock \- establish temporary exclusive lock
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "int neosc_pcsc_lock(void *ctx);"
.SH DESCRIPTION
The
.BR neosc_pcsc_lock()
function establishes a temporary exclusive lock for given CCID connection. Locks should be kept as short as possible to allow other clients to be able to access the YubiKey in a timely manner.
.SH RETURN VALUE
The
.BR neosc_pcsc_lock()
function returns zero in case of success and -1 in case of any error.
.SH SEE ALSO
.BR neosc_pcsc_unlock (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
