.TH NEOSC_UTIL_ID2URI 3  2015-04-10 "" ""
.SH NAME
neosc_util_id2uri \- cunvert uri id to url prefix string
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "char *neosc_util_id2uri(int id);"
.SH DESCRIPTION
The
.BR neosc_util_id2uri()
function converts the given uri id to an url prefix string.
.SH RETURN VALUE
The
.BR neosc_util_id2uri()
function returns a pointer to the url prefix or an empty string.
.SH SEE ALSO
.BR neosc_util_uri2id (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
