.TH NEOSC_SHA1INIT 3  2015-04-10 "" ""
.SH NAME
neosc_sha1init \- initialize SHA1 hash
.SH SYNOPSIS
.nf
.B #include <libneosc.h>
.sp
.BI "void neosc_sha1init(NEOSC_SHA1DATA *ptr);"
.SH DESCRIPTION
The
.BR neosc_sha1init()
function initializes the hash processing structure for subsequent use.
.SH SEE ALSO
.BR neosc_sha1next (3),
.BR neosc_sha1end (3),
.BR neosc_sha1 (3)
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
